# Generated by Django 3.1.5 on 2021-04-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_reg_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='reg',
            name='usertype',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
