# Generated by Django 3.1.5 on 2021-04-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room',
            new_name='rm',
        ),
    ]
