# Generated by Django 3.1.5 on 2021-04-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_auto_20210426_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='rm',
            name='des',
            field=models.CharField(default='', max_length=100),
        ),
    ]
