# Generated by Django 3.1.5 on 2021-04-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_bk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bk',
            name='rm_num',
            field=models.CharField(default='', max_length=100),
        ),
    ]
