# Generated by Django 3.1.5 on 2021-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_rm_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bk',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
