# Generated by Django 3.1.5 on 2021-04-29 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_bk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rm',
            name='rg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.reg'),
            preserve_default=False,
        ),
    ]
