# Generated by Django 3.1.5 on 2021-04-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0011_rm_rg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rm',
            name='rg',
        ),
    ]
