# Generated by Django 3.1.5 on 2021-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0012_remove_rm_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bk',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
