# Generated by Django 3.1.5 on 2021-05-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0013_auto_20210429_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='bk',
            name='total',
            field=models.CharField(default='', max_length=100),
        ),
    ]
