# Generated by Django 3.1.5 on 2021-05-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0014_bk_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='pt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.bk')),
                ('rg1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.reg')),
                ('rm1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.rm')),
            ],
        ),
    ]
