# Generated by Django 3.1.5 on 2021-05-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0015_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pt',
            name='Payment',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
