# Generated by Django 3.1.5 on 2021-05-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0016_pt_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt',
            name='Payment',
            field=models.CharField(default='Paid', max_length=100),
        ),
    ]
